#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MathScripter.Resource", IsApplication=true)]

namespace MathScripter
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MathDrawer.Resource.String.ApplicationName = global::MathScripter.Resource.String.ApplicationName;
			global::MathDrawer.Resource.String.Hello = global::MathScripter.Resource.String.Hello;
			global::MathExecutor.Resource.String.ApplicationName = global::MathScripter.Resource.String.ApplicationName;
			global::MathExecutor.Resource.String.Hello = global::MathScripter.Resource.String.Hello;
			global::MathRecognizer.Resource.String.ApplicationName = global::MathScripter.Resource.String.ApplicationName;
			global::MathRecognizer.Resource.String.Hello = global::MathScripter.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int clear = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int less = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int more = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ok = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int power = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rect = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int remove = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int root = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sqrpower = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int animationButton = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int cameraButton = 2131099666;
			
			// aapt resource value: 0x7f060001
			public const int cameraView = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int captureButton = 2131099648;
			
			// aapt resource value: 0x7f060013
			public const int editButton = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int expressionButton = 2131099660;
			
			// aapt resource value: 0x7f060005
			public const int expressionEdit = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int expressionView = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int graphButton = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int graphView = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int imageView1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int keyboardview = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int leftPanel = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout2 = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int resultButton = 2131099661;
			
			// aapt resource value: 0x7f060009
			public const int rightGraphPanel = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int rightPanel = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int stepsButton = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int textView1 = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Camera = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EquationKeyboard = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ExpressionEdit = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Graph = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Camera = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int CaptureImage = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int ImageParsingError = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
